# Generated by Django 3.1 on 2022-05-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uaername',
            new_name='username',
        ),
    ]
